#!/bin/bash
set -e
set -o pipefail
grep require scripts/import.ts \
  | awk -F 'require' '{print $2}' \
  | awk -F '(' '{print $2}' \
  | awk -F ')' '{print $1}' \
  | sed 's/"//g' \
  | sed "s/'//g" \